version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:8000 backend.app.main:app
    ports:
      - "8000:8000"
    env_file:
      - backend/app/settings/.env.ubuntu
      - backend/app/settings/.env.business
    depends_on:
      - database

  database:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    command: redis-server /usr/local/etc/redis/redis.conf
volumes:
  postgres_data:




